### ISSUE TITLE
installation_bundle_url does not support latest URL scheme

### ISSUE THREAD

**Issue by maxlapides** [bitrise-steplib/bitrise-step-flutter-installer#22]
The latest Flutter SDK is available here: https://flutter.dev/docs/development/tools/sdk/releases?tab=macos
You can see on that page that 2.2.0 is available here: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.0-stable.zip

In my `bitrise.yml`, I updated the `installation_bundle_url` accordingly:

```
- flutter-installer:
    inputs:
      - installation_bundle_url: >-
          https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.0-stable.zip
      - version: stable
```

This produces this error:

```
Downloading and unarchiving Flutter from installation bundle: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_2.2.0-stable.zip
failed to download and unarchive bundle, error: invalid path, expecting it to begin with: flutter_infra
```
